.github/dependabot.yml

Change interval from weekly -> monthly

build: update dependabot schedule

---

.github/workflows/continuous-deployment.yml
package.json

- Update actions to their latest versions
- Remove actions/cache in favour of using the combo pnpm/action-setup and actions/setup-node with `cache: pnpm`
- Add pnpm to package.json#engines

build: improve workflows

---

.github/workflows/continuous-deployment.yml

Test if publish works with unchanged author and comitter names

chore(pipeline): Author names rollback

---

.github/workflows/continuous-deployment.yml

NPM publish failed: NODE_AUTH_TOKEN vs NPM_TOKEN

chore(pipeline): NODE_AUTH_TOKEN vs NPM_TOKEN

---

proprietary/design-tokens/src/imported/common/viewport/xl.json

Removed composition token experiment, because breaks build

Removed composition token experiment, because breaks build

---

proprietary/design-tokens/build/build-tokens.mjs

Fix for calc transform

---

.changeset/cuddly-shrimps-repair.md
package.json

Dit is denk ik het lijstje met nieuwe features die we gaan aanbieden met LUX 1.0. Graag even doornemen en kijken of dit klopt.

chore: create changeset for first release

---

packages/web-components-react/README.md
packages/web-components-react/package.json
packages/web-components-stencil/README.md
packages/web-components-stencil/package.json

Publish web components and React wrapped web components

chore(release): NPM Publish prep

---

.github/workflows/continuous-deployment.yml

Added pnpm config _authToken lines

chore(releases): Update continuous-deployment.yml

---

.github/ISSUE_TEMPLATE/new_component_template.md

Extend issue template with DOD

chore(github): Extend issue template with DOD

---

.github/pull_request_template.md

Create a default PR template which applies to all Pull Requests

chore: create PR template

---

SEMVER.md

Update semver docs with canary releases

chore(docs): Update semver docs with canary releases

---

.github/ISSUE_TEMPLATE/new_component_template.md
packages/components-react/README.md
packages/components-react/package.json
packages/components-react/src/index.ts
packages/components-react/vite.config.ts
packages/storybook/package.json
pnpm-lock.yaml
proprietary/design-tokens/README.md
proprietary/font/README.md

- Utrecht React components toegevoegd

chore(components): Utrecht React components toevoegen

---

.changeset/perfect-zoos-dance.md
proprietary/design-tokens/src/imported/nl/utrecht-form-field.json

Wijziging tokens: stijling invalid form field
- ~~[ ] New features/components and bugfixes are covered by tests~~
- ~~[ ] Definition of Done is checked~~

feat(design tokens): Nieuwe stijling form field invalid

---

.changeset/stale-impalas-notice.md
proprietary/design-tokens/src/imported/$metadata.json
proprietary/design-tokens/src/imported/$themes.json
proprietary/design-tokens/src/imported/nl/utrecht-pre-heading.json

Nieuwe tokens: component utrecht pre heading
Voor de tickets https://github.com/nl-design-system/lux/issues/282 en https://github.com/nl-design-system/lux/issues/283
- ~~[ ] New features/components and bugfixes are covered by tests~~
- ~~[ ] Definition of Done is checked~~

feat(design tokens): Tokens voor heading group

---

.changeset/soft-peaches-collect.md
proprietary/design-tokens/src/imported/$metadata.json
proprietary/design-tokens/src/imported/$themes.json
proprietary/design-tokens/src/imported/nl/utrecht-fieldset.json

Nieuwe tokens: utrecht component fieldset
Relevant voor ticket: https://github.com/nl-design-system/lux/issues/298

Fieldset tokens toevoegen

---

packages/components-react/src/alert/Alert.tsx

alert icons added

---

packages/components-react/src/section/Section.css

remove align items from section

---

packages/components-react/src/alert/Alert.tsx

Console.error fix over de clip-rule en fill-rule

fix: change svg path properties

---

packages/storybook/config/preview.tsx
packages/storybook/src/react-components/alert/alert.stories.tsx
packages/storybook/src/react-components/button/button.stories.tsx
packages/storybook/src/react-components/checkbox/checkbox.stories.tsx
packages/storybook/src/react-components/document/document.stories.tsx
packages/storybook/src/react-components/form-field-checkbox/form-field-checkbox.stories.tsx
packages/storybook/src/react-components/form-field-description/form-field-description.stories.tsx
packages/storybook/src/react-components/form-field-error-message/form-field-error-message.stories.tsx
packages/storybook/src/react-components/form-field-label/form-field-label.stories.tsx
packages/storybook/src/react-components/form-field-radio-group/form-field-radio-group.stories.tsx
packages/storybook/src/react-components/form-field-radio-option/form-field-radio-option.stories.tsx
packages/storybook/src/react-components/form-field-select/form-field-select.stories.tsx
packages/storybook/src/react-components/form-field-textbox/form-field-textbox.stories.tsx
packages/storybook/src/react-components/form-field/form-field.stories.tsx
packages/storybook/src/react-components/heading-group/heading-group.stories.tsx
packages/storybook/src/react-components/heading/heading.stories.tsx
packages/storybook/src/react-components/link/link.stories.tsx
packages/storybook/src/react-components/paragraph/paragraph.stories.tsx
packages/storybook/src/react-components/pre-heading/pre-heading.stories.tsx
packages/storybook/src/react-components/section/section.stories.tsx
packages/storybook/src/react-components/select/select.stories.tsx
packages/storybook/src/react-components/textbox/textbox.stories.tsx

Badges in Storybook voor de React componenten.
- ~~[ ] New features/components and bugfixes are covered by tests~~
- ~~[ ] Changesets are created~~
- ~~[ ] Definition of Done is checked~~

chore(storybook): add correct badges to stories

---

proprietary/design-tokens/src/imported/nl/utrecht-alert.json
proprietary/design-tokens/src/imported/nl/utrecht-text-input.json
proprietary/design-tokens/src/imported/product/EVA.json

**Wijziging tokens:**
- Hover kleur van EVA thema met hexcode ipv een donkere shade over de kleur heen.
- Border van de invalid text-input rood ipv zwart

Token update Eva

---

.changeset/selfish-coins-tan.md
packages/components-react/src/icon/FallbackIcon.tsx
packages/components-react/src/icon/Icon.tsx
packages/components-react/src/icon/test/Icon.spec.tsx

Afronding Icon component fixes

---

packages/storybook/config/preview.tsx
packages/storybook/config/themes.ts
packages/storybook/src/documentation/developer/community-component-aanleveren.md
proprietary/design-tokens/src/imported/product/KOOP.json

1. Naam in KOOP.json was: `product/MijnOverheid`, aangepast naar `product/KOOP`.
2. KOOP thema toegevoegd aan de thema lijst in Storybook.

feat: configured KOOP theme

---

.changeset/selfish-coins-tan.md
packages/components-react/CHANGELOG.md
packages/components-react/package.json
packages/storybook/CHANGELOG.md
packages/storybook/package.json

Added 1.0.1 release of components-react and 1.0.0 of storybook packages

---

.changeset/moody-sheep-mix.md

Add changeset for select focus outline fix

---

.changeset/silver-glasses-kneel.md
packages/components-react/src/form-field-checkbox/FormFieldCheckbox.scss
packages/components-react/src/form-field-checkbox/FormFieldCheckbox.tsx

React components/formfield checkbox specificity

---

package.json
pnpm-lock.yaml

Update pnpm to v10

---

.changeset/tall-geckos-compare.md
packages/components-react/src/radio-button/RadioButton.css
packages/components-react/src/radio-button/RadioButton.tsx

Radiobutton size improvements

---

.changeset/odd-apes-grow.md
packages/components-react/src/checkbox/Checkbox.css
packages/components-react/src/form-field-checkbox/FormFieldCheckbox.scss
packages/storybook/src/react-components/form-field-checkbox/form-field-checkbox.mdx
packages/storybook/src/react-components/form-field-checkbox/form-field-checkbox.stories.tsx

Remove z-index to ensure that border and hover are visible
